version: "2.1"
services:
  server:
    build: .
    image: spring
    ports:
      - 8080:8080
    network_mode: "host"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql
    ports:
      - 3306:3306
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=matchscore
      - MYSQL_USER=matchscore
      - MYSQL_PASSWORD=P4rnupQDiMaL5eoLjXDxiF5RShGZNDpA
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      interval: 10s
      timeout: 2s
      retries: 10
