-- users
insert into users(id,email,username,password_hash,first_name,last_name,enabled) values(1,"test1@mail.com","test1","$2a$11$0nQ/LK5J4BkL1jL/8u85Je8HvzH7/sxG1JXh/l2gwHm6x0gcBh4SO","Jan","Testowy",true);
insert into users(id,email,username,password_hash,first_name,last_name,enabled) values(2,"test2@mail.com","test2","$2a$11$0nQ/LK5J4BkL1jL/8u85Je8HvzH7/sxG1JXh/l2gwHm6x0gcBh4SO","Jakub","Testowy",true);
insert into users(id,email,username,password_hash,first_name,last_name,enabled) values(3,"test3@mail.com","test3","$2a$11$0nQ/LK5J4BkL1jL/8u85Je8HvzH7/sxG1JXh/l2gwHm6x0gcBh4SO","Maciej","Testowy",true);
insert into users(id,email,username,password_hash,first_name,last_name,enabled) values(4,"test4@mail.com","test4","$2a$11$0nQ/LK5J4BkL1jL/8u85Je8HvzH7/sxG1JXh/l2gwHm6x0gcBh4SO","Rafał","Testowy",true);

-- roles
insert into roles(id,`name`) values(1,"ROLE_USER");
insert into roles(id,`name`) values(2,"ROLE_ADMIN");

-- user roles
insert into user_roles(user_id,role_id) values(1,1);
insert into user_roles(user_id,role_id) values(2,1);
insert into user_roles(user_id,role_id) values(3,1);
insert into user_roles(user_id,role_id) values(4,1);
insert into user_roles(user_id,role_id) values(1,2);
insert into user_roles(user_id,role_id) values(2,2);

-- league categories
insert into league_categories(id,`name`) values(1,"ligi centralne");
insert into league_categories(id,`name`) values(2,"III ligi");
insert into league_categories(id,`name`) values(3,"dolnośląski ZPN");
insert into league_categories(id,`name`) values(4,"kujawsko-pomorski ZPN");
insert into league_categories(id,`name`) values(5,"lubelski ZPN");
insert into league_categories(id,`name`) values(6,"lubuski ZPN");
insert into league_categories(id,`name`) values(7,"łódzki ZPN");
insert into league_categories(id,`name`) values(8,"małopolski ZPN");
insert into league_categories(id,`name`) values(9,"mazowiecki ZPN");
insert into league_categories(id,`name`) values(10,"opolski ZPN");
insert into league_categories(id,`name`) values(11,"podkarpacki ZPN");
insert into league_categories(id,`name`) values(12,"podlaski ZPN");
insert into league_categories(id,`name`) values(13,"pomorski ZPN");
insert into league_categories(id,`name`) values(14,"śląski ZPN");
insert into league_categories(id,`name`) values(15,"świętokrzyski ZPN");
insert into league_categories(id,`name`) values(16,"warmińsko-mazurski ZPN");
insert into league_categories(id,`name`) values(17,"wielkopolski ZPN");
insert into league_categories(id,`name`) values(18,"zachodniopomorski ZPN");

-- leagues
-- ligi centralne
insert into leagues(id,`name`,category_id) values(1,"Ekstraklasa",1);
insert into leagues(id,`name`,category_id) values(2,"I liga",1);
insert into leagues(id,`name`,category_id) values(3,"II liga",1);
-- III ligi
insert into leagues(id,`name`,category_id) values(4,"III liga grupa I",2);
insert into leagues(id,`name`,category_id) values(5,"III liga grupa II",2);
insert into leagues(id,`name`,category_id) values(6,"III liga grupa III",2);
insert into leagues(id,`name`,category_id) values(7,"III liga grupa IV",2);
-- dolnośląski ZPN
insert into leagues(id,`name`,category_id) values(8,"IV liga wschód",3);
insert into leagues(id,`name`,category_id) values(9,"IV liga zachód",3);
insert into leagues(id,`name`,category_id) values(10,"Klasa okręgowa Jelenia Góra",3);
insert into leagues(id,`name`,category_id) values(11,"Klasa okręgowa Legnica",3);
insert into leagues(id,`name`,category_id) values(12,"Klasa okręgowa Wałbrzych",3);
insert into leagues(id,`name`,category_id) values(13,"Klasa okręgowa Wrocław",3);
insert into leagues(id,`name`,category_id) values(14,"Klasa A Jelenia Góra I",3);
insert into leagues(id,`name`,category_id) values(15,"Klasa A Jelenia Góra II",3);
insert into leagues(id,`name`,category_id) values(16,"Klasa A Jelenia Góra III",3);
insert into leagues(id,`name`,category_id) values(17,"Klasa A Legnica I",3);
insert into leagues(id,`name`,category_id) values(18,"Klasa A Legnica II",3);
insert into leagues(id,`name`,category_id) values(19,"Klasa A Legnica III",3);
insert into leagues(id,`name`,category_id) values(20,"Klasa A Wałbrzych I",3);
insert into leagues(id,`name`,category_id) values(21,"Klasa A Wałbrzych II",3);
insert into leagues(id,`name`,category_id) values(22,"Klasa A Wałbrzych III",3);
insert into leagues(id,`name`,category_id) values(23,"Klasa A Wrocław I",3);
insert into leagues(id,`name`,category_id) values(24,"Klasa A Wrocław II",3);
insert into leagues(id,`name`,category_id) values(25,"Klasa A Wrocław III",3);
insert into leagues(id,`name`,category_id) values(26,"Klasa A Wrocław IV",3);
insert into leagues(id,`name`,category_id) values(27,"Klasa B Jelenia Góra I",3);
insert into leagues(id,`name`,category_id) values(28,"Klasa B Jelenia Góra II",3);
insert into leagues(id,`name`,category_id) values(29,"Klasa B Jelenia Góra III",3);
insert into leagues(id,`name`,category_id) values(30,"Klasa B Jelenia Góra IV",3);
insert into leagues(id,`name`,category_id) values(31,"Klasa B Legnica I",3);
insert into leagues(id,`name`,category_id) values(32,"Klasa B Legnica II",3);
insert into leagues(id,`name`,category_id) values(33,"Klasa B Legnica III",3);
insert into leagues(id,`name`,category_id) values(34,"Klasa B Legnica IV",3);
insert into leagues(id,`name`,category_id) values(35,"Klasa B Legnica V",3);
insert into leagues(id,`name`,category_id) values(36,"Klasa B Wałbrzych I",3);
insert into leagues(id,`name`,category_id) values(37,"Klasa B Wałbrzych II",3);
insert into leagues(id,`name`,category_id) values(38,"Klasa B Wałbrzych III",3);
insert into leagues(id,`name`,category_id) values(39,"Klasa B Wałbrzych IV",3);
insert into leagues(id,`name`,category_id) values(40,"Klasa B Wrocław I",3);
insert into leagues(id,`name`,category_id) values(41,"Klasa B Wrocław II",3);
insert into leagues(id,`name`,category_id) values(42,"Klasa B Wrocław III",3);
insert into leagues(id,`name`,category_id) values(43,"Klasa B Wrocław IV",3);
insert into leagues(id,`name`,category_id) values(44,"Klasa B Wrocław V",3);
insert into leagues(id,`name`,category_id) values(45,"Klasa B Wrocław VI",3);
insert into leagues(id,`name`,category_id) values(46,"Klasa B Wrocław VII",3);
insert into leagues(id,`name`,category_id) values(47,"Klasa B Wrocław VIII",3);
insert into leagues(id,`name`,category_id) values(48,"Klasa B Wrocław IX",3);
insert into leagues(id,`name`,category_id) values(49,"Klasa C Środa Śląska",3);
insert into leagues(id,`name`,category_id) values(50,"Klasa C Wrocław",3);
-- kujawsko-pomorski ZPN
insert into leagues(id,`name`,category_id) values(51,"IV liga",4);
insert into leagues(id,`name`,category_id) values(52,"Klasa okręgowa I",4);
insert into leagues(id,`name`,category_id) values(53,"Klasa okręgowa II",4);
insert into leagues(id,`name`,category_id) values(54,"Klasa A Bydgoszcz I",4);
insert into leagues(id,`name`,category_id) values(55,"Klasa A Bydgoszcz II",4);
insert into leagues(id,`name`,category_id) values(56,"Klasa A Toruń",4);
insert into leagues(id,`name`,category_id) values(57,"Klasa A Włocławek I",4);
insert into leagues(id,`name`,category_id) values(58,"Klasa A Włocławek II",4);
insert into leagues(id,`name`,category_id) values(59,"Klasa B Bydgoszcz I",4);
insert into leagues(id,`name`,category_id) values(60,"Klasa B Bydgoszcz II",4);
insert into leagues(id,`name`,category_id) values(61,"Klasa B Bydgoszcz III",4);
insert into leagues(id,`name`,category_id) values(62,"Klasa B Bydgoszcz IV",4);
insert into leagues(id,`name`,category_id) values(63,"Klasa B Bydgoszcz V",4);
insert into leagues(id,`name`,category_id) values(64,"Klasa B Toruń",4);
-- lubelski ZPN
insert into leagues(id,`name`,category_id) values(65,"IV liga",5);
insert into leagues(id,`name`,category_id) values(66,"Klasa okręgowa Biała Podlaska",5);
insert into leagues(id,`name`,category_id) values(67,"Klasa okręgowa Chełm",5);
insert into leagues(id,`name`,category_id) values(68,"Klasa okręgowa Lublin",5);
insert into leagues(id,`name`,category_id) values(69,"Klasa okręgowa Zamość",5);
insert into leagues(id,`name`,category_id) values(70,"Klasa A Biała Podlaska I",5);
insert into leagues(id,`name`,category_id) values(71,"Klasa A Biała Podlaska II",5);
insert into leagues(id,`name`,category_id) values(72,"Klasa A Chełm",5);
insert into leagues(id,`name`,category_id) values(73,"Klasa A Lublin I",5);
insert into leagues(id,`name`,category_id) values(74,"Klasa A Lublin II",5);
insert into leagues(id,`name`,category_id) values(75,"Klasa A Lublin III",5);
insert into leagues(id,`name`,category_id) values(76,"Klasa A Zamość",5);
insert into leagues(id,`name`,category_id) values(77,"Klasa B Biała Podlaska I",5);
insert into leagues(id,`name`,category_id) values(78,"Klasa B Biała Podlaska II",5);
insert into leagues(id,`name`,category_id) values(79,"Klasa B Lublin I",5);
insert into leagues(id,`name`,category_id) values(80,"Klasa B Lublin II",5);
insert into leagues(id,`name`,category_id) values(81,"Klasa B Lublin III",5);
insert into leagues(id,`name`,category_id) values(82,"Klasa B Lublin IV",5);
insert into leagues(id,`name`,category_id) values(83,"Klasa B Zamość I",5);
insert into leagues(id,`name`,category_id) values(84,"Klasa B Zamość II",5);
-- lubuski ZPN
insert into leagues(id,`name`,category_id) values(85,"IV liga",6);
insert into leagues(id,`name`,category_id) values(86,"Klasa okręgowa Gorzów Wielkopolski",6);
insert into leagues(id,`name`,category_id) values(87,"Klasa okręgowa Zielona Góra",6);
insert into leagues(id,`name`,category_id) values(88,"Klasa A Gorzów Wielkopolski I",6);
insert into leagues(id,`name`,category_id) values(89,"Klasa A Gorzów Wielkopolski II",6);
insert into leagues(id,`name`,category_id) values(90,"Klasa A Gorzów Wielkopolski III",6);
insert into leagues(id,`name`,category_id) values(91,"Klasa A Zielona Góra I",6);
insert into leagues(id,`name`,category_id) values(92,"Klasa A Zielona Góra II",6);
insert into leagues(id,`name`,category_id) values(93,"Klasa A Zielona Góra III",6);
insert into leagues(id,`name`,category_id) values(94,"Klasa A Zielona Góra IV",6);
insert into leagues(id,`name`,category_id) values(95,"Klasa B Gorzów Wielkopolski I",6);
insert into leagues(id,`name`,category_id) values(96,"Klasa B Gorzów Wielkopolski II",6);
insert into leagues(id,`name`,category_id) values(97,"Klasa B Krosno Odrzańskie",6);
insert into leagues(id,`name`,category_id) values(98,"Klasa B Nowa Sól",6);
insert into leagues(id,`name`,category_id) values(99,"Klasa B Świebodzin",6);
insert into leagues(id,`name`,category_id) values(100,"Klasa B Zielona Góra",6);
insert into leagues(id,`name`,category_id) values(101,"Klasa B Żagań",6);
insert into leagues(id,`name`,category_id) values(102,"Klasa B Żary",6);
-- łódzki ZPN
insert into leagues(id,`name`,category_id) values(103,"IV liga",7);
insert into leagues(id,`name`,category_id) values(104,"Klasa okręgowa Łódź",7);
insert into leagues(id,`name`,category_id) values(105,"Klasa okręgowa Piotrków Trybunalski",7);
insert into leagues(id,`name`,category_id) values(106,"Klasa okręgowa Sieradz",7);
insert into leagues(id,`name`,category_id) values(107,"Klasa okręgowa Skierniewice",7);
insert into leagues(id,`name`,category_id) values(108,"Klasa A Łódź I",7);
insert into leagues(id,`name`,category_id) values(109,"Klasa A Łódź II",7);
insert into leagues(id,`name`,category_id) values(110,"Klasa A Łódź III",7);
insert into leagues(id,`name`,category_id) values(111,"Klasa A Piotrków Trybunalski I",7);
insert into leagues(id,`name`,category_id) values(112,"Klasa A Piotrków Trybunalski II",7);
insert into leagues(id,`name`,category_id) values(113,"Klasa A Sieradz I",7);
insert into leagues(id,`name`,category_id) values(114,"Klasa A Sieradz II",7);
insert into leagues(id,`name`,category_id) values(115,"Klasa A Skierniewice",7);
insert into leagues(id,`name`,category_id) values(116,"Klasa B Łódź I",7);
insert into leagues(id,`name`,category_id) values(117,"Klasa B Łódź II",7);
insert into leagues(id,`name`,category_id) values(118,"Klasa B Łódź III",7);
insert into leagues(id,`name`,category_id) values(119,"Klasa B Piotrków Trybunalski I",7);
insert into leagues(id,`name`,category_id) values(120,"Klasa B Piotrków Trybunalski II",7);
insert into leagues(id,`name`,category_id) values(121,"Klasa B Sieradz I",7);
insert into leagues(id,`name`,category_id) values(122,"Klasa B Sieradz II",7);
insert into leagues(id,`name`,category_id) values(123,"Klasa B Sieradz III",7);
insert into leagues(id,`name`,category_id) values(124,"Klasa B Sieradz IV",7);
insert into leagues(id,`name`,category_id) values(125,"Klasa B Skierniewice I",7);
insert into leagues(id,`name`,category_id) values(126,"Klasa B Skierniewice II",7);
-- małopolski ZPN
insert into leagues(id,`name`,category_id) values(127,"IV liga wschód",8);
insert into leagues(id,`name`,category_id) values(128,"IV liga zachód",8);
insert into leagues(id,`name`,category_id) values(129,"Klasa okręgowa Kraków I",8);
insert into leagues(id,`name`,category_id) values(130,"Klasa okręgowa Kraków II",8);
insert into leagues(id,`name`,category_id) values(131,"Klasa okręgowa Kraków III",8);
insert into leagues(id,`name`,category_id) values(132,"Klasa okręgowa Nowy Sącz I",8);
insert into leagues(id,`name`,category_id) values(133,"Klasa okręgowa Nowy Sącz II",8);
insert into leagues(id,`name`,category_id) values(134,"Klasa okręgowa Tarnów I",8);
insert into leagues(id,`name`,category_id) values(135,"Klasa okręgowa Tarnów II",8);
insert into leagues(id,`name`,category_id) values(136,"Klasa okręgowa Wadowice",8);
insert into leagues(id,`name`,category_id) values(137,"Klasa A Chrzanów",8);
insert into leagues(id,`name`,category_id) values(138,"Klasa A Kraków I",8);
insert into leagues(id,`name`,category_id) values(139,"Klasa A Kraków II",8);
insert into leagues(id,`name`,category_id) values(140,"Klasa A Kraków III",8);
insert into leagues(id,`name`,category_id) values(141,"Klasa A Limanowa",8);
insert into leagues(id,`name`,category_id) values(142,"Klasa A Myślenice",8);
insert into leagues(id,`name`,category_id) values(143,"Klasa A Nowy Sącz",8);
insert into leagues(id,`name`,category_id) values(144,"Klasa A Nowy Sącz-Gorlice",8);
insert into leagues(id,`name`,category_id) values(145,"Klasa A Olkusz",8);
insert into leagues(id,`name`,category_id) values(146,"Klasa A Oświęcim",8);
insert into leagues(id,`name`,category_id) values(147,"Klasa A Podhale",8);
insert into leagues(id,`name`,category_id) values(148,"Klasa A Tarnów I",8);
insert into leagues(id,`name`,category_id) values(149,"Klasa A Tarnów II",8);
insert into leagues(id,`name`,category_id) values(150,"Klasa A Tarnów III",8);
insert into leagues(id,`name`,category_id) values(151,"Klasa A Tarnów IV",8);
insert into leagues(id,`name`,category_id) values(152,"Klasa A Wadowice",8);
insert into leagues(id,`name`,category_id) values(153,"Klasa A Wieliczka",8);
insert into leagues(id,`name`,category_id) values(154,"Klasa B Chrzanów",8);
insert into leagues(id,`name`,category_id) values(155,"Klasa B Kraków I",8);
insert into leagues(id,`name`,category_id) values(156,"Klasa B Kraków II",8);
insert into leagues(id,`name`,category_id) values(157,"Klasa B Kraków III",8);
insert into leagues(id,`name`,category_id) values(158,"Klasa B Kraków IV",8);
insert into leagues(id,`name`,category_id) values(159,"Klasa B Limanowa",8);
insert into leagues(id,`name`,category_id) values(160,"Klasa B Myślenice I",8);
insert into leagues(id,`name`,category_id) values(161,"Klasa B Myślenice II",8);
insert into leagues(id,`name`,category_id) values(162,"Klasa B Nowy Sącz",8);
insert into leagues(id,`name`,category_id) values(163,"Klasa B Olkusz I",8);
insert into leagues(id,`name`,category_id) values(164,"Klasa B Olkusz II",8);
insert into leagues(id,`name`,category_id) values(165,"Klasa B Oświęcim",8);
insert into leagues(id,`name`,category_id) values(166,"Klasa B Podhale I",8);
insert into leagues(id,`name`,category_id) values(167,"Klasa B Podhale II",8);
insert into leagues(id,`name`,category_id) values(168,"Klasa B Tarnów I",8);
insert into leagues(id,`name`,category_id) values(169,"Klasa B Tarnów II",8);
insert into leagues(id,`name`,category_id) values(170,"Klasa B Tarnów III",8);
insert into leagues(id,`name`,category_id) values(171,"Klasa B Tarnów IV",8);
insert into leagues(id,`name`,category_id) values(172,"Klasa B Wadowice I",8);
insert into leagues(id,`name`,category_id) values(173,"Klasa B Wadowice II",8);
insert into leagues(id,`name`,category_id) values(174,"Klasa B Wieliczka",8);
insert into leagues(id,`name`,category_id) values(175,"Klasa C Wadowice",8);
insert into leagues(id,`name`,category_id) values(176,"Klasa C Wieliczka",8);
-- mazowiecki ZPN
insert into leagues(id,`name`,category_id) values(177,"IV liga południe",9);
insert into leagues(id,`name`,category_id) values(178,"IV liga północ",9);
insert into leagues(id,`name`,category_id) values(179,"Klasa okręgowa Ciechanów-Ostrołęka",9);
insert into leagues(id,`name`,category_id) values(180,"Klasa okręgowa Płock",9);
insert into leagues(id,`name`,category_id) values(181,"Klasa okręgowa Radom",9);
insert into leagues(id,`name`,category_id) values(182,"Klasa okręgowa Siedlce",9);
insert into leagues(id,`name`,category_id) values(183,"Klasa okręgowa Warszawa I",9);
insert into leagues(id,`name`,category_id) values(184,"Klasa okręgowa Warszawa II",9);
insert into leagues(id,`name`,category_id) values(185,"Klasa A Ciechanów-Ostrołęka",9);
insert into leagues(id,`name`,category_id) values(186,"Klasa A Płock",9);
insert into leagues(id,`name`,category_id) values(187,"Klasa A Radom I",9);
insert into leagues(id,`name`,category_id) values(188,"Klasa A Radom II",9);
insert into leagues(id,`name`,category_id) values(189,"Klasa A Siedlce",9);
insert into leagues(id,`name`,category_id) values(190,"Klasa A Warszawa I",9);
insert into leagues(id,`name`,category_id) values(191,"Klasa A Warszawa II",9);
insert into leagues(id,`name`,category_id) values(192,"Klasa A Warszawa III",9);
insert into leagues(id,`name`,category_id) values(193,"Klasa A Warszawa IV",9);
insert into leagues(id,`name`,category_id) values(194,"Klasa B Ciechanów",9);
insert into leagues(id,`name`,category_id) values(195,"Klasa B Ostrołęka",9);
insert into leagues(id,`name`,category_id) values(196,"Klasa B Płock",9);
insert into leagues(id,`name`,category_id) values(197,"Klasa B Radom I",9);
insert into leagues(id,`name`,category_id) values(198,"Klasa B Radom II",9);
insert into leagues(id,`name`,category_id) values(199,"Klasa B Siedlce",9);
insert into leagues(id,`name`,category_id) values(200,"Klasa B Warszawa I",9);
insert into leagues(id,`name`,category_id) values(201,"Klasa B Warszawa II",9);
insert into leagues(id,`name`,category_id) values(202,"Klasa B Warszawa III",9);
insert into leagues(id,`name`,category_id) values(203,"Klasa B Warszawa IV",9);
-- opolski ZPN
insert into leagues(id,`name`,category_id) values(204,"IV liga",10);
insert into leagues(id,`name`,category_id) values(205,"Klasa okręgowa I",10);
insert into leagues(id,`name`,category_id) values(206,"Klasa okręgowa II",10);
insert into leagues(id,`name`,category_id) values(207,"Klasa A Opole I",10);
insert into leagues(id,`name`,category_id) values(208,"Klasa A Opole II",10);
insert into leagues(id,`name`,category_id) values(209,"Klasa A Opole III",10);
insert into leagues(id,`name`,category_id) values(210,"Klasa A Opole IV",10);
insert into leagues(id,`name`,category_id) values(211,"Klasa A Opole V",10);
insert into leagues(id,`name`,category_id) values(212,"Klasa A Opole VI",10);
insert into leagues(id,`name`,category_id) values(213,"Klasa B Opole I",10);
insert into leagues(id,`name`,category_id) values(214,"Klasa B Opole II",10);
insert into leagues(id,`name`,category_id) values(215,"Klasa B Opole III",10);
insert into leagues(id,`name`,category_id) values(216,"Klasa B Opole IV",10);
insert into leagues(id,`name`,category_id) values(217,"Klasa B Opole V",10);
insert into leagues(id,`name`,category_id) values(218,"Klasa B Opole VI",10);
insert into leagues(id,`name`,category_id) values(219,"Klasa B Opole VII",10);
insert into leagues(id,`name`,category_id) values(220,"Klasa B Opole VIII",10);
insert into leagues(id,`name`,category_id) values(221,"Klasa B Opole IX",10);
insert into leagues(id,`name`,category_id) values(222,"Klasa B Opole X",10);
insert into leagues(id,`name`,category_id) values(223,"Klasa B Opole XI",10);
insert into leagues(id,`name`,category_id) values(224,"Klasa B Opole XII",10);
-- podkarpacki ZPN
insert into leagues(id,`name`,category_id) values(225,"IV liga",11);
insert into leagues(id,`name`,category_id) values(226,"Klasa okręgowa Dębica",11);
insert into leagues(id,`name`,category_id) values(227,"Klasa okręgowa Jarosław",11);
insert into leagues(id,`name`,category_id) values(228,"Klasa okręgowa Krosno",11);
insert into leagues(id,`name`,category_id) values(229,"Klasa okręgowa Rzeszów",11);
insert into leagues(id,`name`,category_id) values(230,"Klasa okręgowa Stalowa Wola",11);
insert into leagues(id,`name`,category_id) values(231,"Klasa A Dębica",11);
insert into leagues(id,`name`,category_id) values(232,"Klasa A Jarosław",11);
insert into leagues(id,`name`,category_id) values(233,"Klasa A Krosno I",11);
insert into leagues(id,`name`,category_id) values(234,"Klasa A Krosno II",11);
insert into leagues(id,`name`,category_id) values(235,"Klasa A Krosno III",11);
insert into leagues(id,`name`,category_id) values(236,"Klasa A Lubaczów",11);
insert into leagues(id,`name`,category_id) values(237,"Klasa A Przemyśl",11);
insert into leagues(id,`name`,category_id) values(238,"Klasa A Przeworsk",11);
insert into leagues(id,`name`,category_id) values(239,"Klasa A Rzeszów I",11);
insert into leagues(id,`name`,category_id) values(240,"Klasa A Rzeszów II",11);
insert into leagues(id,`name`,category_id) values(241,"Klasa A Rzeszów III",11);
insert into leagues(id,`name`,category_id) values(242,"Klasa A Stalowa Wola I",11);
insert into leagues(id,`name`,category_id) values(243,"Klasa A Stalowa Wola II",11);
insert into leagues(id,`name`,category_id) values(244,"Klasa B Dębica I",11);
insert into leagues(id,`name`,category_id) values(245,"Klasa B Dębica II",11);
insert into leagues(id,`name`,category_id) values(246,"Klasa B Jarosław",11);
insert into leagues(id,`name`,category_id) values(247,"Klasa B Krosno I",11);
insert into leagues(id,`name`,category_id) values(248,"Klasa B Krosno II",11);
insert into leagues(id,`name`,category_id) values(249,"Klasa B Krosno III",11);
insert into leagues(id,`name`,category_id) values(250,"Klasa B Krosno IV",11);
insert into leagues(id,`name`,category_id) values(251,"Klasa B Krosno V",11);
insert into leagues(id,`name`,category_id) values(252,"Klasa B Krosno VI",11);
insert into leagues(id,`name`,category_id) values(253,"Klasa B Lubaczów",11);
insert into leagues(id,`name`,category_id) values(254,"Klasa B Przemyśl",11);
insert into leagues(id,`name`,category_id) values(255,"Klasa B Przeworsk",11);
insert into leagues(id,`name`,category_id) values(256,"Klasa B Rzeszów I",11);
insert into leagues(id,`name`,category_id) values(257,"Klasa B Rzeszów II",11);
insert into leagues(id,`name`,category_id) values(258,"Klasa B Rzeszów III",11);
insert into leagues(id,`name`,category_id) values(259,"Klasa B Rzeszów IV",11);
insert into leagues(id,`name`,category_id) values(260,"Klasa B Rzeszów V",11);
insert into leagues(id,`name`,category_id) values(261,"Klasa B Rzeszów VI",11);
insert into leagues(id,`name`,category_id) values(262,"Klasa B Rzeszów VII",11);
insert into leagues(id,`name`,category_id) values(263,"Klasa B Stalowa Wola I",11);
insert into leagues(id,`name`,category_id) values(264,"Klasa B Stalowa Wola II",11);
insert into leagues(id,`name`,category_id) values(265,"Klasa B Stalowa Wola III",11);
-- podlaski ZPN
insert into leagues(id,`name`,category_id) values(266,"IV liga",12);
insert into leagues(id,`name`,category_id) values(267,"Klasa okręgowa",12);
insert into leagues(id,`name`,category_id) values(268,"Klasa A podlaska I",12);
insert into leagues(id,`name`,category_id) values(269,"Klasa A podlaska II",12);
-- pomorski ZPN
insert into leagues(id,`name`,category_id) values(270,"IV liga",13);
insert into leagues(id,`name`,category_id) values(271,"Klasa okręgowa Gdańsk I",13);
insert into leagues(id,`name`,category_id) values(272,"Klasa okręgowa Gdańsk II",13);
insert into leagues(id,`name`,category_id) values(273,"Klasa okręgowa Słupsk",13);
insert into leagues(id,`name`,category_id) values(274,"Klasa A Gdańsk I",13);
insert into leagues(id,`name`,category_id) values(275,"Klasa A Gdańsk II",13);
insert into leagues(id,`name`,category_id) values(276,"Klasa A Gdańsk III",13);
insert into leagues(id,`name`,category_id) values(277,"Klasa A Gdańsk IV",13);
insert into leagues(id,`name`,category_id) values(278,"Klasa A Słupsk I",13);
insert into leagues(id,`name`,category_id) values(279,"Klasa A Słupsk II",13);
insert into leagues(id,`name`,category_id) values(280,"Klasa B Gdańsk I",13);
insert into leagues(id,`name`,category_id) values(281,"Klasa B Gdańsk II",13);
insert into leagues(id,`name`,category_id) values(282,"Klasa B Gdańsk III",13);
insert into leagues(id,`name`,category_id) values(283,"Klasa B Gdańsk IV",13);
insert into leagues(id,`name`,category_id) values(284,"Klasa B Gdańsk V",13);
insert into leagues(id,`name`,category_id) values(285,"Klasa B Malbork I",13);
insert into leagues(id,`name`,category_id) values(286,"Klasa B Malbork II",13);
insert into leagues(id,`name`,category_id) values(287,"Klasa B Słupsk I",13);
insert into leagues(id,`name`,category_id) values(288,"Klasa B Słupsk II",13);
-- śląski ZPN
insert into leagues(id,`name`,category_id) values(289,"IV liga grupa I",14);
insert into leagues(id,`name`,category_id) values(290,"IV liga grupa II",14);
insert into leagues(id,`name`,category_id) values(291,"Klasa okręgowa I Bytom-Zabrze",14);
insert into leagues(id,`name`,category_id) values(292,"Klasa okręgowa II Częstochowa-Lubliniec",14);
insert into leagues(id,`name`,category_id) values(293,"Klasa okręgowa III Racibórz-Rybnik",14);
insert into leagues(id,`name`,category_id) values(294,"Klasa okręgowa IV Katowice-Sosnowiec",14);
insert into leagues(id,`name`,category_id) values(295,"Klasa okręgowa V Bielsko-Biała-Tychy",14);
insert into leagues(id,`name`,category_id) values(296,"Klasa okręgowa VI Skoczów-Żywiec",14);
insert into leagues(id,`name`,category_id) values(297,"Klasa A Bielsko-Biała",14);
insert into leagues(id,`name`,category_id) values(298,"Klasa A Bytom",14);
insert into leagues(id,`name`,category_id) values(299,"Klasa A Częstochowa I",14);
insert into leagues(id,`name`,category_id) values(300,"Klasa A Częstochowa II",14);
insert into leagues(id,`name`,category_id) values(301,"Klasa A Katowice",14);
insert into leagues(id,`name`,category_id) values(302,"Klasa A Lubliniec",14);
insert into leagues(id,`name`,category_id) values(303,"Klasa A Racibórz",14);
insert into leagues(id,`name`,category_id) values(304,"Klasa A Rybnik",14);
insert into leagues(id,`name`,category_id) values(305,"Klasa A Skoczów",14);
insert into leagues(id,`name`,category_id) values(306,"Klasa A Sosnowiec",14);
insert into leagues(id,`name`,category_id) values(307,"Klasa A Tychy",14);
insert into leagues(id,`name`,category_id) values(308,"Klasa A Zabrze",14);
insert into leagues(id,`name`,category_id) values(309,"Klasa A Żywiec",14);
insert into leagues(id,`name`,category_id) values(310,"Klasa B Bielsko-Biała",14);
insert into leagues(id,`name`,category_id) values(311,"Klasa B Bytom I",14);
insert into leagues(id,`name`,category_id) values(312,"Klasa B Bytom II",14);
insert into leagues(id,`name`,category_id) values(313,"Klasa B Częstochowa I",14);
insert into leagues(id,`name`,category_id) values(314,"Klasa B Częstochowa II",14);
insert into leagues(id,`name`,category_id) values(315,"Klasa B Katowice",14);
insert into leagues(id,`name`,category_id) values(316,"Klasa B Lubliniec",14);
insert into leagues(id,`name`,category_id) values(317,"Klasa B Racibórz",14);
insert into leagues(id,`name`,category_id) values(318,"Klasa B Rybnik",14);
insert into leagues(id,`name`,category_id) values(319,"Klasa B Skoczów",14);
insert into leagues(id,`name`,category_id) values(320,"Klasa B Sosnowiec",14);
insert into leagues(id,`name`,category_id) values(321,"Klasa B Tychy",14);
insert into leagues(id,`name`,category_id) values(322,"Klasa B Zabrze",14);
insert into leagues(id,`name`,category_id) values(323,"Klasa B Żywiec",14);
insert into leagues(id,`name`,category_id) values(324,"Klasa C Racibórz I",14);
insert into leagues(id,`name`,category_id) values(325,"Klasa C Racibórz II",14);
insert into leagues(id,`name`,category_id) values(326,"Klasa C Rybnik",14);
insert into leagues(id,`name`,category_id) values(327,"Klasa C Zabrze",14);
-- świętokrzyski ZPN
insert into leagues(id,`name`,category_id) values(328,"IV liga",15);
insert into leagues(id,`name`,category_id) values(329,"Klasa okręgowa",15);
insert into leagues(id,`name`,category_id) values(330,"Klasa A Kielce I",15);
insert into leagues(id,`name`,category_id) values(331,"Klasa A Kielce II",15);
insert into leagues(id,`name`,category_id) values(332,"Klasa A Sandomierz",15);
insert into leagues(id,`name`,category_id) values(333,"Klasa B Kielce I",15);
insert into leagues(id,`name`,category_id) values(334,"Klasa B Kielce II",15);
insert into leagues(id,`name`,category_id) values(335,"Klasa B Sandomierz",15);
-- warmińsko-mazurski ZPN
insert into leagues(id,`name`,category_id) values(336,"IV liga",16);
insert into leagues(id,`name`,category_id) values(337,"Klasa okręgowa I",16);
insert into leagues(id,`name`,category_id) values(338,"Klasa okręgowa II",16);
insert into leagues(id,`name`,category_id) values(339,"Klasa A I",16);
insert into leagues(id,`name`,category_id) values(340,"Klasa A II",16);
insert into leagues(id,`name`,category_id) values(341,"Klasa A III",16);
insert into leagues(id,`name`,category_id) values(342,"Klasa A IV",16);
insert into leagues(id,`name`,category_id) values(343,"Klasa B I",16);
insert into leagues(id,`name`,category_id) values(344,"Klasa B II",16);
insert into leagues(id,`name`,category_id) values(345,"Klasa B III",16);
insert into leagues(id,`name`,category_id) values(346,"Klasa B IV",16);
-- wielkopolski ZPN
insert into leagues(id,`name`,category_id) values(347,"IV liga",17);
insert into leagues(id,`name`,category_id) values(348,"V liga I",17);
insert into leagues(id,`name`,category_id) values(349,"V liga II",17);
insert into leagues(id,`name`,category_id) values(350,"V liga III",17);
insert into leagues(id,`name`,category_id) values(351,"Klasa okręowa I",17);
insert into leagues(id,`name`,category_id) values(352,"Klasa okręgowa II",17);
insert into leagues(id,`name`,category_id) values(353,"Klasa okręgowa III",17);
insert into leagues(id,`name`,category_id) values(354,"Klasa okręgowa IV",17);
insert into leagues(id,`name`,category_id) values(355,"Klasa okręgowa V",17);
insert into leagues(id,`name`,category_id) values(356,"Klasa okręgowa VI",17);
insert into leagues(id,`name`,category_id) values(357,"Klasa A I",17);
insert into leagues(id,`name`,category_id) values(358,"Klasa A II",17);
insert into leagues(id,`name`,category_id) values(359,"Klasa A III",17);
insert into leagues(id,`name`,category_id) values(360,"Klasa A IV",17);
insert into leagues(id,`name`,category_id) values(361,"Klasa A V",17);
insert into leagues(id,`name`,category_id) values(362,"Klasa A VI",17);
insert into leagues(id,`name`,category_id) values(363,"Klasa A VII",17);
insert into leagues(id,`name`,category_id) values(364,"Klasa A VIII",17);
insert into leagues(id,`name`,category_id) values(365,"Klasa B I",17);
insert into leagues(id,`name`,category_id) values(366,"Klasa B II",17);
insert into leagues(id,`name`,category_id) values(367,"Klasa B III",17);
insert into leagues(id,`name`,category_id) values(368,"Klasa B IV",17);
insert into leagues(id,`name`,category_id) values(369,"Klasa B V",17);
insert into leagues(id,`name`,category_id) values(370,"Klasa B VI",17);
insert into leagues(id,`name`,category_id) values(371,"Klasa B VII",17);
insert into leagues(id,`name`,category_id) values(372,"Klasa B VIII",17);
insert into leagues(id,`name`,category_id) values(373,"Klasa B IX",17);
insert into leagues(id,`name`,category_id) values(374,"Klasa B X",17);
insert into leagues(id,`name`,category_id) values(375,"Klasa B XI",17);
-- zachodniopomorski ZPN
insert into leagues(id,`name`,category_id) values(376,"IV liga",18);
insert into leagues(id,`name`,category_id) values(377,"Klasa okręgowa Koszalin III",18);
insert into leagues(id,`name`,category_id) values(378,"Klasa okręowa Koszalin IV",18);
insert into leagues(id,`name`,category_id) values(379,"Klasa okręgowa Szczecin I",18);
insert into leagues(id,`name`,category_id) values(380,"Klasa okręgowa Szczecin II",18);
insert into leagues(id,`name`,category_id) values(381,"Klasa A Koszalin VIII",18);
insert into leagues(id,`name`,category_id) values(382,"Klasa A Koszalin IX",18);
insert into leagues(id,`name`,category_id) values(383,"Klasa A Koszalin X",18);
insert into leagues(id,`name`,category_id) values(384,"Klasa A Koszalin XI",18);
insert into leagues(id,`name`,category_id) values(385,"Klasa A Szczecin I",18);
insert into leagues(id,`name`,category_id) values(386,"Klasa A Szczecin II",18);
insert into leagues(id,`name`,category_id) values(387,"Klasa A Szczecin III",18);
insert into leagues(id,`name`,category_id) values(388,"Klasa A Szczecin IV",18);
insert into leagues(id,`name`,category_id) values(389,"Klasa A Szczecin V",18);
insert into leagues(id,`name`,category_id) values(390,"Klasa A Szczecin VI",18);
insert into leagues(id,`name`,category_id) values(391,"Klasa A Szczecin VII",18);
insert into leagues(id,`name`,category_id) values(392,"Klasa B Szczecin I",18);
insert into leagues(id,`name`,category_id) values(393,"Klasa B Szczecin II",18);
insert into leagues(id,`name`,category_id) values(394,"Klasa B Szczecin III",18);
insert into leagues(id,`name`,category_id) values(395,"Klasa B Szczecin IV",18);

-- teams
-- Ekstraklasa
insert into teams(id,`name`,league_id) values(1,"Śląsk Wrocław",1);
insert into teams(id,`name`,league_id) values(2,"Jagiellonia Białystok",1);
insert into teams(id,`name`,league_id) values(3,"Pogoń Szczecin",1);
insert into teams(id,`name`,league_id) values(4,"Cracovia",1);
insert into teams(id,`name`,league_id) values(5,"Legia Warszawa",1);
insert into teams(id,`name`,league_id) values(6,"Lech Poznań",1);
insert into teams(id,`name`,league_id) values(7,"Piast Gliwice",1);
insert into teams(id,`name`,league_id) values(8,"Wisła Kraków",1);
insert into teams(id,`name`,league_id) values(9,"Górnik Zabrze",1);
insert into teams(id,`name`,league_id) values(10,"Lechia Gdańsk",1);
insert into teams(id,`name`,league_id) values(11,"Wisła Płock",1);
insert into teams(id,`name`,league_id) values(12,"Raków Częstochowa",1);
insert into teams(id,`name`,league_id) values(13,"Zagłębie Lubin",1);
insert into teams(id,`name`,league_id) values(14,"Arka Gdynia",1);
insert into teams(id,`name`,league_id) values(15,"ŁKS Łódź",1);
insert into teams(id,`name`,league_id) values(16,"Korona Kielce",1);
-- I liga
insert into teams(id,`name`,league_id) values(17,"Stal Mielec",2);
insert into teams(id,`name`,league_id) values(18,"Radomiak Radom",2);
insert into teams(id,`name`,league_id) values(19,"Miedź Legnica",2);
insert into teams(id,`name`,league_id) values(20,"Warta Poznań",2);
insert into teams(id,`name`,league_id) values(21,"Puszcza Niepołomice",2);
insert into teams(id,`name`,league_id) values(22,"Stomil Olsztyn",2);
insert into teams(id,`name`,league_id) values(23,"Wigry Suwałki",2);
insert into teams(id,`name`,league_id) values(24,"GKS Bełchatów",2);
insert into teams(id,`name`,league_id) values(25,"Zagłębie Sosnowiec",2);
insert into teams(id,`name`,league_id) values(26,"GKS 1962 Jastrzębie",2);
insert into teams(id,`name`,league_id) values(27,"Podbeskidzie Bielsko-Biała",2);
insert into teams(id,`name`,league_id) values(28,"Bruk-Bet Termalica Nieciecza",2);
insert into teams(id,`name`,league_id) values(29,"Sandecja Nowy Sącz",2);
insert into teams(id,`name`,league_id) values(30,"GKS Tychy",2);
insert into teams(id,`name`,league_id) values(31,"Olimpia Grudziądz",2);
insert into teams(id,`name`,league_id) values(32,"Chojniczanka Chojnice",2);
insert into teams(id,`name`,league_id) values(33,"Chrobry Głogów",2);
insert into teams(id,`name`,league_id) values(34,"Odra Opole",2);
-- II liga
insert into teams(id,`name`,league_id) values(35,"Znicz Pruszków",3);
insert into teams(id,`name`,league_id) values(36,"Stal Rzeszów",3);
insert into teams(id,`name`,league_id) values(37,"Górnik Łęczna",3);
insert into teams(id,`name`,league_id) values(38,"Błękitni Stargard",3);
insert into teams(id,`name`,league_id) values(39,"Garbarnia Kraków",3);
insert into teams(id,`name`,league_id) values(40,"Resovia",3);
insert into teams(id,`name`,league_id) values(41,"Widzew Łódź",3);
insert into teams(id,`name`,league_id) values(42,"Olimpia Elbląg",3);
insert into teams(id,`name`,league_id) values(43,"Bytovia Bytów",3);
insert into teams(id,`name`,league_id) values(44,"GKS Katowice",3);
insert into teams(id,`name`,league_id) values(45,"Elana Toruń",3);
insert into teams(id,`name`,league_id) values(46,"Pogoń Siedlce",3);
insert into teams(id,`name`,league_id) values(47,"Lech II Poznań",3);
insert into teams(id,`name`,league_id) values(48,"Skra Częstochowa",3);
insert into teams(id,`name`,league_id) values(49,"Górnik Polkowice",3);
insert into teams(id,`name`,league_id) values(50,"Stal Stalowa Wola",3);
insert into teams(id,`name`,league_id) values(51,"Leginovia Legionowo",3);
insert into teams(id,`name`,league_id) values(52,"Gryf Wejherowo",3);
-- III liga grupa I
insert into teams(id,`name`,league_id) values(53,"Sokół Ostróda",4);
insert into teams(id,`name`,league_id) values(54,"Świt Nowy Dwór Mazowiecki",4);
insert into teams(id,`name`,league_id) values(55,"Sokół Aleksandrów Łódzki",4);
insert into teams(id,`name`,league_id) values(56,"Legia II Warszawa",4);
insert into teams(id,`name`,league_id) values(57,"Pelikan Łowicz",4);
insert into teams(id,`name`,league_id) values(58,"Huragan Morąg",4);
insert into teams(id,`name`,league_id) values(59,"Unia Skierniewice",4);
insert into teams(id,`name`,league_id) values(60,"Broń Radom",4);
insert into teams(id,`name`,league_id) values(61,"Concordia Elbląg",4);
insert into teams(id,`name`,league_id) values(62,"Lechia Tomaszów Mazowiecki",4);
insert into teams(id,`name`,league_id) values(63,"Polonia Warszawa",4);
insert into teams(id,`name`,league_id) values(64,"Ursus Warszawa",4);
insert into teams(id,`name`,league_id) values(65,"Olimpia Zambrów",4);
insert into teams(id,`name`,league_id) values(66,"Znicz Biała Piska",4);
insert into teams(id,`name`,league_id) values(67,"RKS Radomsko",4);
insert into teams(id,`name`,league_id) values(68,"Ruch Wysokie Mazowieckie",4);
insert into teams(id,`name`,league_id) values(69,"Pogoń Grodzisk Mazowiecki",4);
insert into teams(id,`name`,league_id) values(70,"KS Wasilków",4);
-- III liga grupa II
insert into teams(id,`name`,league_id) values(71,"KKS 1925 Kalisz",5);
insert into teams(id,`name`,league_id) values(72,"Radunia Stężyca",5);
insert into teams(id,`name`,league_id) values(73,"Kotwica Kołobrzeg",5);
insert into teams(id,`name`,league_id) values(74,"Mieszko Gniezno",5);
insert into teams(id,`name`,league_id) values(75,"Świt Skolwin",5);
insert into teams(id,`name`,league_id) values(76,"Pogoń II Szczecin",5);
insert into teams(id,`name`,league_id) values(77,"Sokół Kleczew",5);
insert into teams(id,`name`,league_id) values(78,"KP Starogard Gdański",5);
insert into teams(id,`name`,league_id) values(79,"Polonia Środa Wielkopolska",5);
insert into teams(id,`name`,league_id) values(80,"Unia Janikowo",5);
insert into teams(id,`name`,league_id) values(81,"Jarota Jarocin",5);
insert into teams(id,`name`,league_id) values(82,"Górnik Konin",5);
insert into teams(id,`name`,league_id) values(83,"Bałtyk Koszalin",5);
insert into teams(id,`name`,league_id) values(84,"Grom Nowy Staw",5);
insert into teams(id,`name`,league_id) values(85,"Chemik Police",5);
insert into teams(id,`name`,league_id) values(86,"Nielba Wągrowiec",5);
insert into teams(id,`name`,league_id) values(87,"Bałtyk Gdynia",5);
insert into teams(id,`name`,league_id) values(88,"Gwardia Koszalin",5);
-- III liga grupa III
insert into teams(id,`name`,league_id) values(89,"Śląsk II Wrocław",6);
insert into teams(id,`name`,league_id) values(90,"Foto-Higiena Gać",6);
insert into teams(id,`name`,league_id) values(91,"ROW 1964 Rybnik",6);
insert into teams(id,`name`,league_id) values(92,"Pniówek Pawłowice Śląskie",6);
insert into teams(id,`name`,league_id) values(93,"Stal Brzeg",6);
insert into teams(id,`name`,league_id) values(94,"Lechia Zielona Góra",6);
insert into teams(id,`name`,league_id) values(95,"Ślęza Wrocław",6);
insert into teams(id,`name`,league_id) values(96,"Rekord Bielsko-Biała",6);
insert into teams(id,`name`,league_id) values(97,"Polonia Bytom",6);
insert into teams(id,`name`,league_id) values(98,"Górnik II Zabrze",6);
insert into teams(id,`name`,league_id) values(99,"Gwarek Tarnowskie Góry",6);
insert into teams(id,`name`,league_id) values(100,"Ruch Zdzieszowiece",6);
insert into teams(id,`name`,league_id) values(101,"Piast Żmigród",6);
insert into teams(id,`name`,league_id) values(102,"Miedź II Legnica",6);
insert into teams(id,`name`,league_id) values(103,"MKS Kluczbork",6);
insert into teams(id,`name`,league_id) values(104,"Zagłębie II Lubin",6);
insert into teams(id,`name`,league_id) values(105,"LZS Starowice Dolne",6);
insert into teams(id,`name`,league_id) values(106,"Ruch Chorzów",6);
-- III liga grupa IV
insert into teams(id,`name`,league_id) values(107,"Korona II Kielce",7);
insert into teams(id,`name`,league_id) values(108,"Siarka Tarnobrzeg",7);
insert into teams(id,`name`,league_id) values(109,"Hetman Zamość",7);
insert into teams(id,`name`,league_id) values(110,"Stal Kraśnik",7);
insert into teams(id,`name`,league_id) values(111,"Wisła Puławy",7);
insert into teams(id,`name`,league_id) values(112,"Hutnik Kraków",7);
insert into teams(id,`name`,league_id) values(113,"KSZO 1929 Ostrowiec Świętokrzyski",7);
insert into teams(id,`name`,league_id) values(114,"Wólczanka Wólka Pełkińska",7);
insert into teams(id,`name`,league_id) values(115,"Sokół Sieniawa",7);
insert into teams(id,`name`,league_id) values(116,"Wisłoka Dębica",7);
insert into teams(id,`name`,league_id) values(117,"Orlęta Radzyń Podlaski",7);
insert into teams(id,`name`,league_id) values(118,"Avia Świdnik",7);
insert into teams(id,`name`,league_id) values(119,"Motor Lublin",7);
insert into teams(id,`name`,league_id) values(120,"Wisła Sandomierz",7);
insert into teams(id,`name`,league_id) values(121,"Podhale Nowy Targ",7);
insert into teams(id,`name`,league_id) values(122,"Chełmianka Chełm",7);
insert into teams(id,`name`,league_id) values(123,"Jutrzenka Giebułtów",7);
insert into teams(id,`name`,league_id) values(124,"Podlasie Biała Podlaska",7);
